language: java
sudo: false
jdk:
- oraclejdk8
notifications:
  email: false
install:
- cd $TRAVIS_BUILD_DIR/ && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
  -B -V
addons:
  sonarqube: true
env:
  global:
  - secure: $SONAR_TOKEN
  - secure: YoCfmXgIikJ6Yue7xYj/PSWW3IxBo7VauAyOI4+Zre1vsYuUByd6Q1bR+rBdA8n86ZHcFfwHgQ5trWON1z8sLzAAiNblferC5Z9ZtV00/ocQ3dCMqNLDG8ev/Zw6NbmKQXJrPh4nFg65Z4xlAtlHLPZE/UyTeVVyO4Vg2WEdVz83enC7EfY9soxSv1J1gEl8ALw4+K8gdzNuZiiT5yJ+A3xf+SEgzfXgrggA3l8vd+IjHIF4Z3hHwPXc60F5lRhoP2G4+K9Z20jcmzL8UBVSRwRgftj4DAtFXBEUJ24L5v3IlRt2ZMzkM0ch1AYhJdYKddjYO/A7xYN4+Irnw5/lGT+fpOuR2QUQLMJd+5J6koSLEnDkNDdJEPFsnahu+s8EGcFrLog3UhGvhhE/WSll2INBajmwuBQ6bTgvO7z/mEDmBCv3CSN2mQTCK9ply9Vsg6CZ4r+mB/iEwX6dVdaQ/FNWSln6gyBI8tW7je2Sn/t+CMDYvJtCQFUsKrK8RtXnmlcXaR/vJcmYTS7ZnApOrmzb96GkygZzUoXWpJAs3RHithlJjMD1i3rnR4nsyjWVAQcvzm2ixRiuEf9ggmfe7ngTZsGy6/nq6RJLA/7iIXpZxJcG2nots7L38JrfbHOtKsbIP7lzEVYg8skspIkRY0NTgKu7Ta4X6IJRquH22L8=
deploy:
  provider: heroku
  api_key:
    secure: X8boBthYewW8qN59TGLp3AHVqQvjZqk8DkzSxKZmx1xMhvZ00aSZCIQNM+wu4UnB4bUfBC7KCJmdWX4h2oNyydQFCSwitYceJqUQVx8HfH4w/Z3QXvcJSyZ96pSBoYTcsEl3SCKQ/gPnZxefeBR2OwkdoY1Fs9lSHcI54H/H3uL5I18qxkmbhdDvszMfHix+rTRvtu35KQpTpf7Oyi8/9EficU8W6a2WBzES/A3+o662S5YqEtS5LzqisP6a3cRN0pn4t5c1tzCzLVizm20H8WVbNP/CuyBXyXSDXn8X1R4ep5UHXf197XsH07vWFZGfe9chuSVG6mU1CEc0Yh5ijOnjHmUCWeg6v3HKels5qTp/t3TzuW3yQIDrW2netJqcBNJjn8gKlb16QtkfDnjfMM3O3U8fnd0BWtIa4tJQIgHhSs2A4IXEtXtjL9X6EdiKfQCMGyYFvGBFZ1iowmlmtDPGVcaaIJe+Y/Z/aKBCIH2mgzAAjDtfE6m2jIVIl+f0y68qNZ1PuYetUDT8HkaNUFJohoHlLP9p9om1dOCoKwjOKNGPCVYq67ltx5zPPd/zhO6wtkNmXHK0wDCS7w8fW0Elw8BG4ecQY/t9N6vR1Wi+zLmfra4ks/eXo06HMgfJxLqiAm0r7alc8A8ivHNIrV5R5zosu3XZzkUw71LnPZ8=

